[package]
name = "crates_io_test_utils"
version = "0.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/crates.io"
description = "Test utilities for crates.io"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
anyhow = "=1.0.102"
bytes = "=1.11.1"
cargo-manifest = "=0.19.1"
chrono = "=0.4.43"
crates_io_api_types = { path = "../crates_io_api_types" }
crates_io_database = { path = "../crates_io_database" }
crates_io_tarball = { path = "../crates_io_tarball", features = ["builder"] }
diesel = "=2.3.6"
diesel-async = "=0.7.4"
semver = "=1.0.27"
serde_json = "=1.0.149"
toml = "=1.0.3"
