[package]
name = "crates_io_fastly"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
reqwest = { version = "=0.12.24", features = ["json"] }
secrecy = "=0.10.3"
thiserror = "=2.0.17"
tracing = "=0.1.41"
