[package]
name = "crates_io_fastly"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
crates_io_version = { path = "../crates_io_version" }
reqwest = { version = "=0.13.2", features = ["json"] }
secrecy = "=0.10.3"
thiserror = "=2.0.18"
tracing = "=0.1.44"
