[package]
name = "crates_io_tarball"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[features]
builder = []

[dependencies]
cargo_toml = "=0.15.3"
derive_deref = "=1.1.1"
flate2 = "=1.0.26"
semver = { version = "=1.0.18", features = ["serde"] }
serde = { version = "=1.0.181", features = ["derive"] }
serde_json = "=1.0.104"
tar = "=0.4.39"
thiserror = "=1.0.44"
toml = "=0.7.6"
tracing = "=0.1.37"

[dev-dependencies]
anyhow = "=1.0.72"
claims = "=0.7.1"
clap = { version = "=4.3.19", features = ["derive", "unicode", "wrap_help"] }
indicatif = { version = "=0.17.6", features = ["rayon"] }
rayon = "=1.7.0"
tracing-subscriber = { version = "=0.3.17", features = ["env-filter"] }
walkdir = "=2.3.3"
