[package]
name = "crates_io_session"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
axum = { version = "=0.8.8", features = ["macros"] }
axum-extra = { version = "=0.12.5", features = ["cookie-signed"] }
base64 = "=0.22.1"
cookie = { version = "=0.18.1", features = ["secure"] }
parking_lot = "=0.12.5"

[dev-dependencies]
