[package]
name = "crates_io_smoke_test"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "=1.0.75"
bytes = "=1.4.0"
clap = { version = "=4.4.0", features = ["derive", "env", "unicode", "wrap_help"] }
crates_io_index = { path = "../crates_io_index" }
reqwest = { version = "=0.11.20", features = ["blocking", "gzip", "json"] }
secrecy = "=0.8.0"
semver = { version = "=1.0.18", features = ["serde"] }
serde = { version = "=1.0.186", features = ["derive"] }
serde_json = "=1.0.105"
tempfile = "=3.8.0"
thiserror = "=1.0.47"
tracing = "=0.1.37"
tracing-subscriber = { version = "=0.3.17", features = ["env-filter"] }
