[package]
name = "crates_io_diesel_helpers"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
diesel = { version = "=2.3.6", features = ["postgres"] }
semver = "=1.0.27"
serde = { version = "=1.0.228", features = ["derive"] }

[dev-dependencies]
crates_io_database = { path = "../crates_io_database" }
