[package]
name = "aws-ip-ranges"
version = "0.0.0"
description = "https://ip-ranges.amazonaws.com/ip-ranges.json as const structs"
license = "MIT OR Apache-2.0"
edition = "2021"
publish = false

[build-dependencies]
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.145"
