[package]
name = "crates_io_test_db"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
crates_io_env_vars = { path = "../crates_io_env_vars" }
diesel = { version = "=2.1.6", features = ["postgres", "r2d2"] }
diesel_migrations = { version = "=2.1.0", features = ["postgres"] }
once_cell = "=1.19.0"
rand = "=0.8.5"
tracing = "=0.1.40"
url = "=2.5.0"
