[package]
name = "crates_io_test_db"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
crates_io_env_vars = { path = "../crates_io_env_vars" }
diesel = { version = "=2.3.6", features = ["postgres", "r2d2"] }
diesel-async = { version = "=0.7.4", features = ["postgres"] }
diesel_migrations = { version = "=2.3.1", features = ["postgres"] }
rand = "=0.9.2"
tracing = "=0.1.44"
url = "=2.5.8"
