[package]
name = "crates_io_test_db"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
crates_io_env_vars = { path = "../crates_io_env_vars" }
diesel = { version = "=2.2.10", features = ["postgres", "r2d2"] }
diesel-async = { version = "=0.5.2", features = ["postgres"] }
diesel_migrations = { version = "=2.2.0", features = ["postgres"] }
rand = "=0.9.1"
tracing = "=0.1.41"
url = "=2.5.4"
