[package]
name = "crates_io_team_repo"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2024"

[lints]
workspace = true

[features]
mock = ["mockall"]

[dependencies]
anyhow = "=1.0.98"
async-trait = "=0.1.88"
mockall = { version = "=0.13.1", optional = true }
reqwest = { version = "=0.12.15", features = ["gzip", "json"] }
serde = { version = "=1.0.219", features = ["derive"] }

[dev-dependencies]
tokio = { version = "=1.45.1", features = ["macros", "rt-multi-thread"] }
