[package]
name = "crates_io_team_repo"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2024"

[lints]
workspace = true

[features]
mock = ["mockall"]

[dependencies]
anyhow = "=1.0.100"
async-trait = "=0.1.89"
mockall = { version = "=0.14.0", optional = true }
reqwest = { version = "=0.12.27", features = ["gzip", "json"] }
serde = { version = "=1.0.228", features = ["derive"] }

[dev-dependencies]
tokio = { version = "=1.48.0", features = ["macros", "rt-multi-thread"] }
