[package]
name = "crates_io_team_repo"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = "=1.0.90"
async-trait = "=0.1.83"
mockall = "=0.13.0"
reqwest = { version = "=0.12.8", features = ["gzip", "json"] }
serde = { version = "=1.0.211", features = ["derive"] }

[dev-dependencies]
tokio = { version = "=1.40.0", features = ["macros", "rt-multi-thread"] }
