name: Smoke Test

on:
  workflow_dispatch:

concurrency:
  group: smoke-test
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.6.0
      - uses: Swatinem/rust-cache@v2.6.2
      - run: cargo build --package crates_io_smoke_test
      - run: cargo run --package crates_io_smoke_test --quiet
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.STAGING_SMOKE_TEST_TOKEN }}
